import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = name => fs.readFileSync(path.join(root, name), 'utf8');
const data = name => JSON.parse(read(`src/data/${name}.json`));
const checking = process.argv.includes('--check');
const generated = new Map();
const cell = value => String(value ?? '-').replace(/\|/g, '\\|')
  .replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\r?\n/g, ' ');
const code = value => `\`${cell(value)}\``;
const table = (head, rows) => [
  `| ${head.join(' | ')} |`, `| ${head.map(() => '---').join(' | ')} |`,
  ...rows.map(row => `| ${row.map(cell).join(' | ')} |`)
].join('\n');
const save = (name, content) => generated.set(`docs/reference/${name}.md`,
  `${content.trim()}\n\n---\n\nGenerated by \`npm run docs:generate\`. Edit the source/configuration or generator, then regenerate; \`npm run docs:check\` detects stale tables.\n`);

const settingsSource = read('src/core/settings.js').match(/SETTINGS_DEFAULTS = Object\.freeze\(\{([\s\S]*?)\}\)/)?.[1];
if (!settingsSource) throw Error('Cannot find settings defaults');
const defaults = Object.fromEntries([...settingsSource.matchAll(/^\s*(\w+):\s*([^,\n]+),?$/gm)]
  .map(([, key, value]) => [key, JSON.parse(value.trim())]));
const settingInfo = {
  residentsPerTilePerFloor: ['1–8, integer', 'Residential capacity per footprint cell per floor'],
  maxPopulation: ['30–1,000, integer', 'Admission cap; reducing it does not evict residents'],
  glowIntensity: ['0.2–2, increments of 0.1', 'Night emissive strength'],
  shadows: ['boolean', 'Real-time renderer shadows'],
  councilTemperature: ['0–1, normalized to 0.01; UI steps 0.05', 'LLM sampling temperature'],
  councilSittingsPerDay: ['1–12, integer', 'Scheduled decision windows per game day'],
  cabinetMotionsPerSitting: ['1–5, integer in Settings', 'Mayor approval cap; all five ministers still receive a call'],
  averageCongestionThreshold: ['0.1–0.9, increments of 0.05', 'Average between-sitting road-planning gate'],
  autoCouncil: ['boolean', 'Scheduled LLM decisions'],
  fitTown: ['boolean', 'Auto-fit acquired land at changes and three-game-hour boundaries'],
  defaultSpeed: ['0, 1, 2, 4, 10, 20, 50, 100', 'Start/reset clock multiplier; 0 pauses'],
  cameraYaw: ['−180–180°, increments of 0.5', 'Stored azimuth'],
  cameraPitch: ['0–80°, integer', 'Stored polar tilt; 0° is overhead'],
  cameraZoom: ['40–500 m, integer', 'Stored camera distance'],
  cameraTargetX: ['−96–96 m, increments of 0.5', 'Stored pan X'],
  cameraTargetZ: ['−80–80 m, increments of 0.5', 'Stored pan Z']
};
for (const key of Object.keys(defaults)) if (!settingInfo[key]) throw Error(`Document the new setting ${key}`);
save('settings', `# Settings reference\n\nSource: [settings.js](../../src/core/settings.js). Keys persist under \`tomm.settings\`; [usage](../user-guide.md#settings-and-persistence) explains live/reset behaviour.\n\n${table(['Key', 'Default', 'Range', 'Meaning'], Object.entries(defaults).map(([key, value]) => [code(key), code(value), ...settingInfo[key]]))}`);

const manifests = read('src/kits/builtinManifests.js');
const routes = new Map();
for (const [, body] of manifests.matchAll(/routes:\s*\{([^}]+)\}/g)) {
  for (const [, intent, plan] of body.matchAll(/([A-Z][A-Z0-9_]+):\s*(?:'([^']+)'|null)/g)) routes.set(intent, plan || null);
}
const direct = manifests.match(/routes:\s*Object\.fromEntries\(\[([\s\S]*?)\]\.map/)?.[1];
if (!direct) throw Error('Cannot find direct built-in routes');
for (const [, intent] of direct.matchAll(/'([A-Z][A-Z0-9_]+)'/g)) routes.set(intent, null);
const meaning = {
  IMAGINE_ARCHETYPE: 'Compose a supported catalogue design; block=<id> or facility=<id> required',
  DEVELOP_HOUSING: 'Refer housing demand to developers; optional block=<housing id>, program=social_housing for public housing',
  OPEN_SHOP: 'Refer viable retail demand; optional tier=<commerce rung>',
  BUILD_OFFICE: 'Refer office/service capacity; optional name and floors',
  TIERUP: 'Advance a commercial rung; optional tier',
  UPGRADE_BUILDING: 'Add an eligible floor within owner/type/zoning constraints',
  RENOVATE: 'Improve quality; optional budget=1..3',
  WING: 'Add a legal adjoining horizontal footprint',
  RESTRUCTURE_BUILDING: 'Reconfigure eligible occupied built capacity',
  BUILD_FACTORY: 'Build a named works; type=<factory id>',
  BUILD_CIVIC: 'Build a public facility; facility=<civic id> when named in evidence',
  EXPAND_CLINIC: 'Legacy civic-capacity expansion route',
  BUILD_LANDMARK: 'Commission a milestone structure; type=<landmark id>',
  EXPAND_LANDMARK: 'Annex an existing landmark; type=<landmark id>',
  UPGRADE_RESOURCE: 'Upgrade/add resource capacity; resource=water|energy|food|fuel, optional eligible kind',
  EXPAND_POWER: 'Expand power network capacity',
  EXPAND_WATER: 'Expand water network capacity',
  EXPAND_SEWAGE: 'Expand sewage network capacity',
  EXTEND_STREET: 'Evaluate and add a useful legal road run',
  EXTEND_FOOTWAY: 'Add a legal walking access link',
  UPGRADE_ROAD: 'Upgrade eligible corridor class; optional class=<road class>',
  BUILD_BRIDGE: 'Connect a legal water gap',
  ADD_PARKING: 'Add eligible kerbside parking',
  PARK_LAND: 'Create parkland',
  PAVE_PLAZA: 'Create a civic square',
  PLANT_TREES: 'Plant eligible foliage',
  INSTALL_LAMP: 'Add a lighting prop',
  DISPATCH_UNITS: 'Respond to current incidents with available units',
  BUILD_TRANSIT: 'Commission transit/depot civic capacity; facility=transit|busdepot',
  ACQUIRE_LAND: 'Acquire an eligible contiguous frontier parcel; preserve serviced-plot discipline',
  ANNEX_EDGE: 'Apply eligible edge land-use planning; zone=<zone id>',
  RAISE_TAX: 'Raise the configured tax policy multiplier',
  CUT_TAX: 'Reduce the tax policy multiplier',
  KEEP_TAX: 'Retain current tax policy',
  HIRE_WORKERS: 'Recruit for measured fundable staff vacancies, not generic unemployment',
  ATTRACT_SETTLERS: 'Promote settlement within housing/resource/admission constraints',
  FUND_INNOVATION: 'Fund the measured research programme',
  TRADE_BUY: 'Import a commodity; commodity=<commodity id>, qty=1..200',
  TRADE_SELL: 'Export a commodity; commodity=<commodity id>, qty=1..200',
  SET_ASIDE_RESERVE: 'Allocate fiscal reserve under existing guards',
  BOND_ISSUE: 'Raise eligible public finance with debt obligations',
  SUBSIDY: 'Apply the existing business-support spending path',
  SLASH_SPENDING: 'Reduce eligible spending scale',
  HOST_EVENT: 'Commission a supported civic event',
  DECLARE_EMERGENCY: 'Set emergency policy/response state',
  STUDY_ROAD: 'Inspect road evidence without a construction commitment',
  STUDY_ECONOMY: 'Inspect fiscal/market evidence',
  STUDY_DEMOGRAPHICS: 'Inspect population/housing evidence',
  STUDY_TRAFFIC: 'Inspect congestion/mobility evidence',
  STUDY_INCIDENTS: 'Inspect current incident evidence',
  SOLICIT_FDI: 'Solicit eligible foreign-investment offers',
  APPROVE_CONCESSION: 'Approve an eligible foreign offer; optional offerId=<offer id>',
  ENACT_SCHEME: 'Start a timed scheme; scheme=<scheme id>',
  END_SCHEME: 'End an active scheme; scheme=<scheme id>',
  PASS_LAW: 'Enact a supported statute; law=<law id>',
  REPEAL_LAW: 'Remove a supported active statute; law=<law id>',
  NO_ACTION: 'Explicitly take no public action',
  BUILD_DISTRICT: 'Plan the existing measured district growth chain',
  REZONE: 'Change eligible land use; zone=residential|commercial|industrial|civic|park',
  UPZONE: 'Raise permitted density',
  CLEAR_LOT: 'Demolish/clear an eligible site with account and occupancy checks'
};
const cabinet = data('cabinet');
for (const intent of routes.keys()) if (!meaning[intent]) throw Error(`Document the new intent ${intent}`);
save('intents', `# Intent reference\n\n${routes.size} canonical intents are declared by [built-in kit routes](../../src/kits/builtinManifests.js) and consumed through [actionRegistry.js](../../src/simulation/actionRegistry.js). The Cabinet column comes from [cabinet.json](../../src/data/cabinet.json). A dash means no explicit default Cabinet ownership; the legacy parser/diagnostic route remains declared. Shared ownership is shown explicitly.\n\nThese are descriptions and syntax, not availability guarantees. Current report evidence, ownership, financing, placement and parameter validation still apply. See [Council flow](../council.md).\n\n${table(['Intent', 'Plan route', 'Default Cabinet', 'Function / parameters'], [...routes].sort(([a],[b])=>a.localeCompare(b)).map(([intent, plan]) => [code(intent), plan ? code(plan) : 'direct', cabinet.departments.filter(d=>d.intents.includes(intent)).map(d=>d.id).join(', ') || '-', meaning[intent]]))}`);

const construction = data('constructionCatalog'), industry = data('industryCatalog');
const civic = data('civicCatalog'), civicRules = data('civicRules');
const schemes = data('council_schemes').schemes, vehicles = data('vehicleCatalog');
const asPairs = obj => Object.entries(obj || {}).map(([key, value]) => `${key}: ${value}`).join(', ') || 'none';
const factoryRows = industry.factoryTypes.map(row=>[
  code(row.id), row.label, code(row.product), row.floors,
  asPairs(industry.inputs[row.product]), row.modules.join(', ')
]);
const buildRows = construction.blocks.map(row=>[code(row.id), row.label, row.kit, row.family,
  (row.footprint || []).join(' × '), (row.modules || []).join(', ')]);
const landmarkSource = read('src/simulation/growth.js').match(/export const LANDMARKS = \{([\s\S]*?)\n\};/)?.[1];
const landmarkRows = landmarkSource ? [...landmarkSource.matchAll(/^\s{2}([\w-]+):\s*\{/gm)].map(([, id])=>[code(id)]) : [];
const policySource = read('src/simulation/policy.js').match(/export const LAWS = \[([\s\S]*?)\n\];/)?.[1];
const lawRows = policySource ? [...policySource.matchAll(/id:\s*'([^']+)'[\s\S]*?label:\s*'([^']+)'/g)].map(([,id,label])=>[code(id),label]) : [];
if (!landmarkRows.length || !lawRows.length) throw Error('Could not extract landmark/law catalogue');
save('catalogues', `# Catalogue reference

## Construction blocks

${construction.blocks.length} rows from [constructionCatalog.json](../../src/data/constructionCatalog.json). Footprints are catalogue dimensions in cells, before any legal variant/plan adjustment; modules require their renderer/consumer.

${table(['Block ID','Label','Kit','Family','Footprint','Modules'], buildRows)}

## Factories and input recipes

${industry.factoryTypes.length} types from [industryCatalog.json](../../src/data/industryCatalog.json). Floors are declared type defaults, not guarantees of a newly selected plan. Recipes are input units per output unit. A dash/none means no declared commodity input in this recipe, not zero operating cost.

${table(['Factory ID','Label','Output','Floors','Inputs per output unit','Visual modules'], factoryRows)}

## Storehouse commodities

Base daily rate is scaled by factory capacity/utilization. Crude oil has no local production rate. Prices are obtained through the separate dynamic price chart.

${table(['Commodity','Label','Capacity','Initial total','Base rate'], industry.commodities.map(id=>[code(id),industry.labels[id]||id,industry.capacity[id],industry.initial[id],industry.rate[id]??'import-only']))}

## Civic facilities

From [civicCatalog.json](../../src/data/civicCatalog.json) and [civicRules.json](../../src/data/civicRules.json). Declared capacity is a base catalogue value; built area, floors, staffing and system rules determine actual service.

${table(['Facility','Label','Base capacity','Capacity kind','Floor cap','Upgrade path'], Object.entries(civic.catalogue).map(([id,row])=>[code(id),row.label,row.capacity,civicRules.capacityKind[id],civicRules.verticalCaps[id],civicRules.upgradePaths[id]?`${civicRules.upgradePaths[id].to} at population ${civicRules.upgradePaths[id].minPopulation}`:'-']))}

## Landmarks

These \`BUILD_LANDMARK type=\` IDs come from [growth.js](../../src/simulation/growth.js). Their feasibility, footprint, population and reserve gates are implemented by that table/planner, not inferred from the label.

${table(['Landmark type'], landmarkRows)}

## Schemes and laws

Schemes from [council_schemes.json](../../src/data/council_schemes.json). Values are configured base amounts; check affordability and prerequisites at enactment.

${table(['Scheme ID','Label','Upfront','Per day','Days','Needs','Effects'],schemes.map(row=>[code(row.id),row.label,row.cost,row.per,row.days,asPairs(row.needs),asPairs(row.effects)]))}

Law IDs from [policy.js](../../src/simulation/policy.js); laws use the declared policy effect path.

${table(['Law ID','Label'],lawRows)}

## Vehicle types

From [vehicleCatalog.json](../../src/data/vehicleCatalog.json). Dimensions below are unscaled catalogue values. Global render/body scale is ${vehicles.scale}; some types also declare their own scale. Availability/procurement is separate from weighted vehicle appearance.

${table(['Type','Role','Unit','Length','Width','Height','Speed factor'],vehicles.types.map(row=>[code(row.id),row.role||'civilian',row.unit||'-',row.length,row.width,row.height,row.speed]))}
`);

const descriptions = {
  buildtime:'Base game-hour schedules and bounded pressure/area/floor terms',
  cabinet:'Department remits, prompt focus, intents, priority mix and Mayor caps',
  citizenContent:'Names, hobbies, traits, occupations and job requirements',
  civicCatalog:'Facility visual and base capacity specifications',
  civicRules:'Capacity kinds, vertical caps and civic transitions',
  constructionCatalog:'Block catalogue, family bills and module premiums',
  council_schemes:'Timed schemes, costs, needs and generic effect keys',
  economyRules:'Tax, pay, spending, finance/agency, municipal fees and credit rules',
  foreignInvestment:'Investors, offer gates and external project declarations',
  growthRules:'Progression/priority gates, density and planning limits',
  incidentRules:'Incident spawn/response and scene time windows',
  industryCatalog:'Factory types, commodity inventories, recipes and production rates',
  industryDemand:'Commodity customer profiles, shared demand ranking, buffers, persistence and input finance',
  kpiRules:'Retained observations and UI scoring targets',
  lifecycleRules:'Ages, education/housing admission, arrivals and campaigns',
  performance:'Render/agent/UI budgets, geometry, caches and retries',
  priceChart:'Base money prices and bounded market response coefficients',
  researchRules:'Research buckets and applied improvement levers',
  resourceRules:'Primary site footprints, levels, output, storage and planning',
  societyRules:'Neighbourhoods, mood, crime, elections and retention',
  transportRules:'Vehicle economics, transit demand, service coverage and fleet caps',
  utilityRules:'Distribution-network cost, capacity, demand and placement patterns',
  vehicleCatalog:'Body dimensions, role/type declarations, speed and spawn weights',
  weather:'Season lengths, state pools and demand/yield/traffic/mood modifiers',
  worldRules:'Plate extent, founding layout range and floor ceilings'
};
const files = fs.readdirSync(path.join(root,'src/data')).filter(name=>name.endsWith('.json')).sort();
for (const file of files) if (!descriptions[file.slice(0,-5)]) throw Error(`Document the data file ${file}`);
const times = data('buildtime'), prices = data('priceChart');
const priceRows = [];
for (const [group,value] of Object.entries(prices)) {
  if (!value || typeof value !== 'object') continue;
  if ('base' in value) priceRows.push([code(group),value.base,asPairs(Object.fromEntries(Object.entries(value).filter(([key])=>key!=='base')))]);
  else for (const [key,row] of Object.entries(value)) if(row&&typeof row==='object'&&'base' in row)
    priceRows.push([code(`${group}.${key}`),row.base,asPairs(Object.fromEntries(Object.entries(row).filter(([key])=>key!=='base')))]);
}
save('data-files', `# Data-file reference\n\nSee [configuration](../configuration.md) for ownership, units and safe changes. All JSON is bundled with the client; new keys need existing consumers or implementation.\n\n${table(['File','Purpose','Top-level sections'],files.map(file=>[`[${file}](../../src/data/${file})`,descriptions[file.slice(0,-5)],Object.keys(data(file.slice(0,-5))).filter(key=>!key.startsWith('$')).join(', ')]))}\n\n## Base build hours\n\nThese are base game hours, not final durations. Area, height, pressure, congestion, fiscal terms and applicable policy can change eligible quotes.\n\n${table(['Plan/type','Base hours','Area coefficient','Floor coefficient'],Object.entries(times.types).map(([id,row])=>[code(id),row.base,row.area??0,row.floors??0]))}\n\n## Base price lookup\n\nThese are dollar-denominated base rows, not final invoices, daily spending or current market quotes. Extra row fields are listed exactly as configured.\n\n${table(['Price key','Base','Other row fields'],priceRows)}\n`);

const pkg = JSON.parse(read('package.json'));
save('scripts', `# npm script reference\n\nRun from the repository root. Browser checks generally need Vite running and \`APP_URL\` pointing at it; script defaults vary. See [testing](../testing.md) for selection and horizon costs.\n\n${table(['Command','Executable'],Object.entries(pkg.scripts).map(([name,command])=>[code(`npm run ${name}`),code(command)]))}`);

let faults = 0;
for (const [name,content] of generated) {
  if (checking) {
    if (!fs.existsSync(path.join(root,name)) || read(name).replace(/\r\n/g,'\n') !== content) {
      console.error(`Stale generated reference: ${name}`); faults++;
    }
  } else {
    fs.mkdirSync(path.dirname(path.join(root,name)), { recursive:true });
    fs.writeFileSync(path.join(root,name),content,'utf8');
  }
}

if (checking) {
  const walk = directory => fs.readdirSync(directory,{withFileTypes:true}).flatMap(entry=>
    entry.isDirectory()?walk(path.join(directory,entry.name)):
      entry.name.endsWith('.md')?[path.join(directory,entry.name)]:[]);
  const documents = ['README.md','CONTRIBUTING.md'].map(name=>path.join(root,name))
    .concat(walk(path.join(root,'docs')));
  const anchors = filename => {
    const counts = new Map();
    return new Set([...read(path.relative(root,filename)).replace(/```[\s\S]*?```/g,'').matchAll(/^#{1,6}\s+(.+)$/gm)].map(([,heading])=>{
      const base = heading.toLowerCase().replace(/[`*]/g,'').replace(/[^\p{L}\p{N}_\-\s]/gu,'').trim().replace(/\s/g,'-');
      const n = counts.get(base)||0; counts.set(base,n+1); return n?`${base}-${n}`:base;
    }));
  };
  for (const file of documents) {
    const body = fs.readFileSync(file,'utf8').replace(/```[\s\S]*?```/g,'');
    for (const [,link] of body.matchAll(/\[[^\]]*\]\(([^)]+)\)/g)) {
      if (/^[a-z][\w+.-]*:/i.test(link)) continue;
      const [target,fragment] = link.split('#');
      const resolved = target ? path.resolve(path.dirname(file),decodeURIComponent(target)):file;
      if (!fs.existsSync(resolved) || (fragment && resolved.endsWith('.md') && !anchors(resolved).has(decodeURIComponent(fragment)))) {
        console.error(`Broken link in ${path.relative(root,file)}: ${link}`); faults++;
      }
    }
  }
  console.log(`Checked ${documents.length} Markdown files, ${generated.size} generated references, ${routes.size} intents, ${construction.blocks.length} blocks, ${Object.keys(defaults).length} settings; ${faults} faults.`);
} else console.log(`Generated ${generated.size} references from current source and JSON.`);
process.exitCode = faults ? 1 : 0;
